bases:
  - environments.yaml

releases:
  - name: nginx-demo-{{ .Environment.Name }}
    namespace: {{ .Environment.Name }}
    atomic: true
    labels:
      app: nginxDemo
    chart: ./charts/nginx-demo
