bases:
  - environments.yaml

releases:
  - name: nginx-demo-{{ .Environment.Name }}
    namespace: {{ .Environment.Name }}
    atomic: true
    labels:
      app: nginxDemo
    chart: ./charts/nginx-demo
    secrets:
      - envs/{{ .Environment.Name }}/secrets.yaml
    values:
      - envs/{{ .Environment.Name }}/values.yaml.gotmpl
